# -------- BUILD STAGE --------
FROM golang:1.25-alpine AS builder

WORKDIR /

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download

COPY . .

RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build CGO_ENABLED=0 go build -o app ./cmd

# -------- RUNTIME STAGE --------
FROM gcr.io/distroless/base-debian12

ENV TZ=Asia/Jakarta

COPY --from=builder /app /app

USER nonroot:nonroot
ENTRYPOINT ["/app"]
